"""estado inicial

Revision ID: 70afc16028e8
Revises: 
Create Date: 2026-10-04 00:55:50.183980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70afc16028e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mentor_user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_slots_mentor_user_id'), 'availability_slots', ['mentor_user_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mentor_settings',
    sa.Column('mentor_user_id', sa.UUID(), nullable=False),
    sa.Column('auto_accept', sa.Boolean(), nullable=False),
    sa.Column('weekly_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('mentor_user_id')
    )
    op.create_table('mentor_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mentor_user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_categories_mentor_user_id'), 'mentor_categories', ['mentor_user_id'], unique=False)
    op.create_table('mentorships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_user_id', sa.UUID(), nullable=False),
    sa.Column('mentor_user_id', sa.UUID(), nullable=False),
    sa.Column('availability_slot_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['availability_slot_id'], ['availability_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('availability_slot_id')
    )
    op.create_index(op.f('ix_mentorships_mentor_user_id'), 'mentorships', ['mentor_user_id'], unique=False)
    op.create_index(op.f('ix_mentorships_student_user_id'), 'mentorships', ['student_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentorships_student_user_id'), table_name='mentorships')
    op.drop_index(op.f('ix_mentorships_mentor_user_id'), table_name='mentorships')
    op.drop_table('mentorships')
    op.drop_index(op.f('ix_mentor_categories_mentor_user_id'), table_name='mentor_categories')
    op.drop_table('mentor_categories')
    op.drop_table('mentor_settings')
    op.drop_table('categories')
    op.drop_index(op.f('ix_availability_slots_mentor_user_id'), table_name='availability_slots')
    op.drop_table('availability_slots')
    # ### end Alembic commands ###
